from pathlib import Path
import yaml

NEGATIVE_INF = -100000.0

PERSPECTIVE_API_KEY = 'AIzaSyCF6zOQddF3GfSluUNmoU6xzIREp7obYPY'

PERSPECTIVE_API_ATTRIBUTES = {
    'TOXICITY'
}

PERSPECTIVE_API_ATTRIBUTES_LOWER = tuple(a.lower() for a in PERSPECTIVE_API_ATTRIBUTES)
